# Yarn configuration for cross-platform compatibility
nodeLinker: node-modules

# Enable PnP fallback for better cross-platform support
pnpMode: loose

# Set registry
npmRegistryServer: "https://registry.npmjs.org"

# Enable global cache
enableGlobalCache: true

# Immutable installs for CI
enableImmutableInstalls: false

# Progress bar settings
enableProgressBars: true
progressBarStyle: default

# Network settings
httpTimeout: 60000
httpRetry: 3

# Install state
installStatePath: .yarn/install-state.gz

# Platform-specific settings
supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - x64
    - arm64
    - ia32